// Code Generated by Sidekick is for learning and experimentation purposes only.
package org.firstinspires.ftc.teamcode;

import com.qualcomm.hardware.rev.RevHubOrientationOnRobot;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.hardware.CRServo;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.IMU;
import com.qualcomm.robotcore.hardware.PIDFCoefficients;
import com.qualcomm.robotcore.hardware.Servo;
import com.qualcomm.robotcore.util.ElapsedTime;
import com.qualcomm.robotcore.util.Range;

import org.firstinspires.ftc.robotcore.external.navigation.AngleUnit;
import org.firstinspires.ftc.robotcore.external.navigation.YawPitchRollAngles;

@Autonomous(name = "Decode 2026: Blue Goal Auto V6 (Anti-Twitch + Steps)", group = "Robot")
public class Decode2026_BlueGoalAuto_Mecanum_Launch_StepTelemetry_V6 extends LinearOpMode {

    // -------------------- DRIVE --------------------
    private DcMotor leftFrontDrive, rightFrontDrive, leftBackDrive, rightBackDrive;
    private IMU imu;

    private double headingError = 0.0;
    private double targetHeading = 0.0;

    private int lfTarget = 0, rfTarget = 0, lbTarget = 0, rbTarget = 0;

    // -------------------- LAUNCHER --------------------
    private DcMotorEx leftLauncher, rightLauncher;
    private CRServo leftFeeder, rightFeeder;
    private Servo diverter;

    // -------------------- INTAKE --------------------
    private DcMotor intake = null;

    // Timers (kept from your working code style)
    ElapsedTime leftFeederTimer = new ElapsedTime();
    ElapsedTime rightFeederTimer = new ElapsedTime();

    // -------------------- CONSTANTS --------------------
    private static final double FEED_TIME_SECONDS = 0.80;
    private static final double STOP_SPEED = 0.0;
    private static final double FULL_SPEED = 1.0;

    private static final double INTAKE_POWER = 1.00;

    private static final double LAUNCHER_CLOSE_TARGET_VELOCITY = 1200; // ticks/sec
    private static final double LAUNCHER_CLOSE_MIN_VELOCITY    = 1175;

    private double launcherTarget = LAUNCHER_CLOSE_TARGET_VELOCITY;
    private double launcherMin    = LAUNCHER_CLOSE_MIN_VELOCITY;

    private static final double LEFT_POSITION  = 0.2962;
    private static final double RIGHT_POSITION = 0.0;

    // -------------------- COUNTS/INCH --------------------
    static final double COUNTS_PER_MOTOR_REV  = 537.7;
    static final double DRIVE_GEAR_REDUCTION  = 1.0;
    static final double WHEEL_DIAMETER_INCHES = 104.0 / 25.4;
    static final double COUNTS_PER_INCH =
            (COUNTS_PER_MOTOR_REV * DRIVE_GEAR_REDUCTION) / (WHEEL_DIAMETER_INCHES * Math.PI);

    // -------------------- TUNABLES --------------------
    static final double DRIVE_SPEED  = 0.80;
    static final double STRAFE_SPEED = 0.60;
    static final double TURN_SPEED   = 0.25;

    static final double HALF_DRIVE_SPEED = 0.40; // half speed for last 18 inches

    static final double HEADING_THRESHOLD_DEG = 1.0;
    static final double P_TURN_GAIN  = 0.02;
    static final double P_DRIVE_GAIN = 0.03;

    static final double MAX_CORRECTION = 0.28;

    // -------------------- HEADINGS --------------------
    static final double HEADING_GOAL_DEG   = 0.0;
    static final double HEADING_LEFT45_DEG = 45.0;

    // -------------------- STEP COUNTER --------------------
    private int stepNum = 0;

    @Override
    public void runOpMode() {

        // -------------------- MAP HARDWARE --------------------
        leftFrontDrive  = hardwareMap.get(DcMotor.class, "left_front_drive");
        rightFrontDrive = hardwareMap.get(DcMotor.class, "right_front_drive");
        leftBackDrive   = hardwareMap.get(DcMotor.class, "left_back_drive");
        rightBackDrive  = hardwareMap.get(DcMotor.class, "right_back_drive");

        leftLauncher  = hardwareMap.get(DcMotorEx.class, "left_launcher");
        rightLauncher = hardwareMap.get(DcMotorEx.class, "right_launcher");
        leftFeeder    = hardwareMap.get(CRServo.class, "left_feeder");
        rightFeeder   = hardwareMap.get(CRServo.class, "right_feeder");
        diverter      = hardwareMap.get(Servo.class, "diverter");
        intake        = hardwareMap.get(DcMotor.class, "intake");

        // -------------------- DIRECTIONS --------------------
        leftFrontDrive.setDirection(DcMotor.Direction.REVERSE);
        rightFrontDrive.setDirection(DcMotor.Direction.FORWARD);
        leftBackDrive.setDirection(DcMotor.Direction.REVERSE);
        rightBackDrive.setDirection(DcMotor.Direction.FORWARD);

        leftLauncher.setDirection(DcMotorSimple.Direction.REVERSE);
        rightFeeder.setDirection(DcMotorSimple.Direction.REVERSE);
        intake.setDirection(DcMotorSimple.Direction.REVERSE);

        // -------------------- IMU INIT --------------------
        RevHubOrientationOnRobot.LogoFacingDirection logoDirection = RevHubOrientationOnRobot.LogoFacingDirection.UP;
        RevHubOrientationOnRobot.UsbFacingDirection usbDirection   = RevHubOrientationOnRobot.UsbFacingDirection.BACKWARD;
        imu = hardwareMap.get(IMU.class, "imu");
        imu.initialize(new IMU.Parameters(new RevHubOrientationOnRobot(logoDirection, usbDirection)));

        // -------------------- ANTI-TWITCH INIT LOGIC --------------------
        // Keep drivetrain FLOAT during INIT (prevents "brake snap" while touching wall).
        setAllZeroPowerBehavior(DcMotor.ZeroPowerBehavior.FLOAT);

        // Ensure everything is explicitly stopped immediately.
        //holdStillInit();

        // Keep motors in a benign mode during INIT.
        setAllModes(DcMotor.RunMode.RUN_WITHOUT_ENCODER);

        // Launcher config (safe to set up during INIT; we still command 0)
        leftLauncher.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        rightLauncher.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        leftLauncher.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        rightLauncher.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        leftLauncher.setPIDFCoefficients(DcMotor.RunMode.RUN_USING_ENCODER, new PIDFCoefficients(300, 0, 0, 10));
        rightLauncher.setPIDFCoefficients(DcMotor.RunMode.RUN_USING_ENCODER, new PIDFCoefficients(300, 0, 0, 10));

        leftFeeder.setPower(STOP_SPEED);
        rightFeeder.setPower(STOP_SPEED);
        diverter.setPosition(LEFT_POSITION);
        //setIntakePower(0.0);

        while (opModeInInit()) {
            // Continuously force 0 so nothing “blips”
            holdStillInit();

            telemetry.addLine("Ready: Decode 2026 Blue Goal Auto V6");
            telemetry.addData("Heading (deg)", "%.1f", getHeading());
            telemetry.addData("Counts/Inch", "%.2f", COUNTS_PER_INCH);
            telemetry.addData("Drive/Strafe/Turn", "%.2f / %.2f / %.2f", DRIVE_SPEED, STRAFE_SPEED, TURN_SPEED);
            telemetry.addLine("Anti-twitch: DRIVE FLOAT + forced zero power");
            telemetry.update();
        }

        if (isStopRequested()) return;

        // -------------------- START: ENABLE NORMAL DRIVE BEHAVIOR --------------------
        imu.resetYaw();

        // Now that match has started, it's safe to use BRAKE and reset encoders.
        setAllZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        setAllModes(DcMotor.RunMode.STOP_AND_RESET_ENCODER);
        setAllModes(DcMotor.RunMode.RUN_USING_ENCODER);

        // ==================== AUTON STEPS (your revised list) ====================

        step(1, "Start: front touching blue goal on launch line; launcher in back");

        step(2, "Back 52 in, hold 0 deg");
        driveStraight(DRIVE_SPEED, -52.0, HEADING_GOAL_DEG);

        setIntakePower(INTAKE_POWER);
        step(3, "Shoot 3 artifacts; wait 3s");
        shoot3ArtifactsAndWait3s();

        step(4, "Turn left to 45 deg");
        turnToHeading(TURN_SPEED, HEADING_LEFT45_DEG);

        step(5, "Forward 36: last 18 at half speed (intake ON)");
        setIntakePower(INTAKE_POWER);
        driveStraight(DRIVE_SPEED, 36.0, HEADING_LEFT45_DEG);
        //driveStraight(HALF_DRIVE_SPEED, 18.0, HEADING_LEFT45_DEG);
        //setIntakePower(0.0);

        step(6, "Back to step 2 pose: back 36; turn to 0 deg");
        driveStraight(DRIVE_SPEED, -36.0, HEADING_LEFT45_DEG);
        turnToHeading(TURN_SPEED, HEADING_GOAL_DEG);

        step(7, "Shoot 3 artifacts; wait 3s");
        shoot3ArtifactsAndWait3s();

        step(8, "Turn left to 45 deg");
        turnToHeading(TURN_SPEED, HEADING_LEFT45_DEG);

        step(9, "Strafe left 26 in, hold 45 deg");
        strafeDistance(STRAFE_SPEED, -26.0, HEADING_LEFT45_DEG);

        step(10, "Forward 36: last 18 at half speed (intake ON)");
        setIntakePower(INTAKE_POWER);
        driveStraight(DRIVE_SPEED, 36.0, HEADING_LEFT45_DEG);
        //driveStraight(HALF_DRIVE_SPEED, 18.0, HEADING_LEFT45_DEG);
        //setIntakePower(0.0);

        step(11, "Back to step 2 pose: back 36; strafe right 26; turn to 0 deg");
        driveStraight(DRIVE_SPEED, -36.0, HEADING_LEFT45_DEG);
        strafeDistance(STRAFE_SPEED, 26.0, HEADING_LEFT45_DEG);
        turnToHeading(TURN_SPEED, HEADING_GOAL_DEG);

        step(12, "Shoot 3 artifacts; wait 3s");
        shoot3ArtifactsAndWait3s();

        step(13, "Turn left to 45 deg");
        turnToHeading(TURN_SPEED, HEADING_LEFT45_DEG);

        step(14, "Strafe left 36 in, hold 45 deg");
        strafeDistance(STRAFE_SPEED, -36.0, HEADING_LEFT45_DEG);

        // Stop everything */
        moveRobot(0.0, 0.0, 0.0);
        stopLauncher();
        setIntakePower(0.0);

        telemetry.addLine("AUTO COMPLETE");
        telemetry.update();
       // sleep(500);
    }

    // =========================================================================================
    // INIT ANTI-TWITCH HELPERS
    // =========================================================================================
    private void holdStillInit() {
        // Drivetrain
        leftFrontDrive.setPower(0);
        rightFrontDrive.setPower(0);
        leftBackDrive.setPower(0);
        rightBackDrive.setPower(0);

        // Shooter/intake
        leftLauncher.setVelocity(0);
        rightLauncher.setVelocity(0);
        leftFeeder.setPower(0);
        rightFeeder.setPower(0);
        //setIntakePower(0.0);
    }

    private void setIntakePower(double power) {
        if (intake != null) intake.setPower(power);
    }

    // =========================================================================================
    // STEP TELEMETRY
    // =========================================================================================
    private void step(int number, String description) {
        stepNum = number;
        telemetry.addLine("--------------------------------");
        telemetry.addData("STEP", "%d", stepNum);
        telemetry.addData("Action", "%s", description);
        telemetry.addData("Heading (deg)", "%.1f", getHeading());
        telemetry.update();
        sleep(150);
    }

    // =========================================================================================
    // LAUNCHER: Shoot 3 + wait 3 seconds
    // =========================================================================================
    private void shoot3ArtifactsAndWait3s() {
        boolean spunUp = spinUpLauncher(1.25);

        if (spunUp && opModeIsActive()) {
            rightFeeder.setPower(FULL_SPEED);
            sleep(1000);

            fireOneShotRight();
            fireOneShotRight();
            fireOneShotRight();

            rightFeeder.setPower(STOP_SPEED);
        }

        sleep(3000);
    }

    private boolean spinUpLauncher(double timeoutSeconds) {
        leftLauncher.setVelocity(launcherTarget);
        rightLauncher.setVelocity(launcherTarget);

        long start = System.currentTimeMillis();
        while (opModeIsActive() && (System.currentTimeMillis() - start) < (long) (timeoutSeconds * 1000.0)) {
            if (rightLauncher.getVelocity() >= launcherMin) return true;

            telemetry.addData("Vel L/R", "%.0f / %.0f", leftLauncher.getVelocity(), rightLauncher.getVelocity());
            telemetry.update();
            sleep(10);
        }
        return rightLauncher.getVelocity() >= launcherMin;
    }

    private void fireOneShotRight() {
        if (!opModeIsActive()) return;

        diverter.setPosition(0.99);
        sleep((long) (FEED_TIME_SECONDS * 500.0));
        diverter.setPosition(0.05);
        sleep((long) (FEED_TIME_SECONDS * 500.0));
    }

    private void stopLauncher() {
        leftLauncher.setVelocity(STOP_SPEED);
        rightLauncher.setVelocity(STOP_SPEED);
        leftFeeder.setPower(STOP_SPEED);
        rightFeeder.setPower(STOP_SPEED);
    }

    // =========================================================================================
    // DRIVE: Encoder moves + IMU heading hold
    // =========================================================================================
    private void driveStraight(double maxDriveSpeed, double distanceInches, double headingDeg) {
        if (!opModeIsActive()) return;

        int moveCounts = (int) Math.round(distanceInches * COUNTS_PER_INCH);

        lfTarget = leftFrontDrive.getCurrentPosition() + moveCounts;
        rfTarget = rightFrontDrive.getCurrentPosition() + moveCounts;
        lbTarget = leftBackDrive.getCurrentPosition() + moveCounts;
        rbTarget = rightBackDrive.getCurrentPosition() + moveCounts;

        setAllTargets(lfTarget, rfTarget, lbTarget, rbTarget);
        setAllModes(DcMotor.RunMode.RUN_TO_POSITION);

        maxDriveSpeed = Math.abs(maxDriveSpeed);
        moveRobot(maxDriveSpeed, 0.0, 0.0);

        while (opModeIsActive() && anyBusy()) {
            double correction = getSteeringCorrection(headingDeg, P_DRIVE_GAIN);
            if (distanceInches < 0) correction *= -1.0;
            correction = Range.clip(correction, -MAX_CORRECTION, MAX_CORRECTION);
            moveRobot(maxDriveSpeed, 0.0, correction);
        }

        moveRobot(0.0, 0.0, 0.0);
        setAllModes(DcMotor.RunMode.RUN_USING_ENCODER);
    }

    private void strafeDistance(double maxStrafeSpeed, double distanceInches, double headingDeg) {
        if (!opModeIsActive()) return;

        int moveCounts = (int) Math.round(distanceInches * COUNTS_PER_INCH);

        // Strafe RIGHT (+): LF+, RF-, LB-, RB+
        lfTarget = leftFrontDrive.getCurrentPosition() + moveCounts;
        rfTarget = rightFrontDrive.getCurrentPosition() - moveCounts;
        lbTarget = leftBackDrive.getCurrentPosition() - moveCounts;
        rbTarget = rightBackDrive.getCurrentPosition() + moveCounts;

        setAllTargets(lfTarget, rfTarget, lbTarget, rbTarget);
        setAllModes(DcMotor.RunMode.RUN_TO_POSITION);

        maxStrafeSpeed = Math.abs(maxStrafeSpeed);
        moveRobot(0.0, maxStrafeSpeed, 0.0);

        while (opModeIsActive() && anyBusy()) {
            double correction = getSteeringCorrection(headingDeg, P_DRIVE_GAIN);
            correction = Range.clip(correction, -MAX_CORRECTION, MAX_CORRECTION);
            moveRobot(0.0, maxStrafeSpeed, correction);
        }

        moveRobot(0.0, 0.0, 0.0);
        setAllModes(DcMotor.RunMode.RUN_USING_ENCODER);
    }

    private void turnToHeading(double maxTurnSpeed, double headingDeg) {
        getSteeringCorrection(headingDeg, P_DRIVE_GAIN);

        while (opModeIsActive() && (Math.abs(headingError) > HEADING_THRESHOLD_DEG)) {
            double turn = getSteeringCorrection(headingDeg, P_TURN_GAIN);
            turn = Range.clip(turn, -maxTurnSpeed, maxTurnSpeed);
            moveRobot(0.0, 0.0, turn);
        }
        moveRobot(0.0, 0.0, 0.0);
    }

    // =========================================================================================
    // DRIVE: Helpers
    // =========================================================================================
    private double getSteeringCorrection(double desiredHeadingDeg, double proportionalGain) {
        targetHeading = desiredHeadingDeg;
        headingError = targetHeading - getHeading();

        while (headingError > 180) headingError -= 360;
        while (headingError <= -180) headingError += 360;

        return Range.clip(headingError * proportionalGain, -1.0, 1.0);
    }

    private void moveRobot(double drive, double strafe, double turn) {
        double lf = drive + strafe - turn;
        double rf = drive - strafe + turn;
        double lb = drive - strafe - turn;
        double rb = drive + strafe + turn;

        double max = Math.max(Math.max(Math.abs(lf), Math.abs(rf)), Math.max(Math.abs(lb), Math.abs(rb)));
        if (max > 1.0) {
            lf /= max; rf /= max; lb /= max; rb /= max;
        }

        leftFrontDrive.setPower(lf);
        rightFrontDrive.setPower(rf);
        leftBackDrive.setPower(lb);
        rightBackDrive.setPower(rb);
    }

    private void setAllTargets(int lf, int rf, int lb, int rb) {
        leftFrontDrive.setTargetPosition(lf);
        rightFrontDrive.setTargetPosition(rf);
        leftBackDrive.setTargetPosition(lb);
        rightBackDrive.setTargetPosition(rb);
    }

    private void setAllModes(DcMotor.RunMode mode) {
        leftFrontDrive.setMode(mode);
        rightFrontDrive.setMode(mode);
        leftBackDrive.setMode(mode);
        rightBackDrive.setMode(mode);
    }

    private void setAllZeroPowerBehavior(DcMotor.ZeroPowerBehavior behavior) {
        leftFrontDrive.setZeroPowerBehavior(behavior);
        rightFrontDrive.setZeroPowerBehavior(behavior);
        leftBackDrive.setZeroPowerBehavior(behavior);
        rightBackDrive.setZeroPowerBehavior(behavior);
    }

    private boolean anyBusy() {
        return leftFrontDrive.isBusy() || rightFrontDrive.isBusy() ||
                leftBackDrive.isBusy()  || rightBackDrive.isBusy();
    }

    private double getHeading() {
        YawPitchRollAngles o = imu.getRobotYawPitchRollAngles();
        return o.getYaw(AngleUnit.DEGREES);
    }

    @SuppressWarnings("unused")
    private void switchDiverterDirection(boolean toRight) {
        diverter.setPosition(toRight ? RIGHT_POSITION : LEFT_POSITION);
    }
}
