// Code Generated by Sidekick is for learning and experimentation purposes only.
package org.firstinspires.ftc.teamcode.notneeded;

import com.qualcomm.hardware.rev.RevHubOrientationOnRobot;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.Disabled;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.hardware.CRServo;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.IMU;
import com.qualcomm.robotcore.hardware.PIDFCoefficients;
import com.qualcomm.robotcore.hardware.Servo;
import com.qualcomm.robotcore.util.ElapsedTime;
import com.qualcomm.robotcore.util.Range;

import org.firstinspires.ftc.robotcore.external.navigation.AngleUnit;
import org.firstinspires.ftc.robotcore.external.navigation.YawPitchRollAngles;

@Autonomous(name = "Auto small Red 31567 New Bot", group = "Robot")
@Disabled
public class AutoSmallRed_31567_old extends LinearOpMode {

    // -------------------- DRIVE --------------------
    private DcMotor leftFrontDrive, rightFrontDrive, leftBackDrive, rightBackDrive;
    private IMU imu;

    private double headingError = 0.0;
    private double targetHeading = 0.0;

    private int lfTarget = 0, rfTarget = 0, lbTarget = 0, rbTarget = 0;

    // -------------------- LAUNCHER (from your TeleOp) --------------------
    private DcMotorEx leftLauncher, rightLauncher;
    private CRServo leftFeeder, rightFeeder;
    private Servo diverter;
    private DcMotor intake = null;

    ElapsedTime leftFeederTimer = new ElapsedTime();
    ElapsedTime rightFeederTimer = new ElapsedTime();

    private enum IntakeState { ON, OFF; }

    private enum LaunchState { IDLE, SPIN_UP, LAUNCH, LAUNCHING, }
    private LaunchState leftLaunchState;
    private LaunchState rightLaunchState;

    private enum DiverterDirection { LEFT, RIGHT; }

    private static final double FEED_TIME_SECONDS = 0.80;
    private static final double STOP_SPEED = 0.0;
    private static final double FULL_SPEED = 1.0;

    private static final double LAUNCHER_CLOSE_TARGET_VELOCITY = 1200; // ticks/sec
    private static final double LAUNCHER_CLOSE_MIN_VELOCITY    = 1175;

    //added for far distance
    final double LAUNCHER_FAR_TARGET_VELOCITY = 1450; //Target velocity for far goal 1400 orig
    final double LAUNCHER_FAR_MIN_VELOCITY = 1425; //minimum required to start a shot for far goal. 1375 orig

    private double launcherTarget = LAUNCHER_FAR_TARGET_VELOCITY;
    private double launcherMin    = LAUNCHER_FAR_MIN_VELOCITY;

    private static final double LEFT_POSITION  = 0.2962;
    private static final double RIGHT_POSITION = 0.0;

    // -------------------- COUNTS/INCH --------------------
    static final double COUNTS_PER_MOTOR_REV  = 537.7;
    static final double DRIVE_GEAR_REDUCTION  = 1.0;
    static final double WHEEL_DIAMETER_INCHES = 104.0 / 25.4;
    static final double COUNTS_PER_INCH =
            (COUNTS_PER_MOTOR_REV * DRIVE_GEAR_REDUCTION) / (WHEEL_DIAMETER_INCHES * Math.PI);

    // -------------------- TUNABLES --------------------
    static final double DRIVE_SPEED  = 0.90;
    static final double STRAFE_SPEED = 0.90;
    static final double TURN_SPEED   = 0.40;

    static final double HEADING_THRESHOLD_DEG = 1.0;
    static final double P_TURN_GAIN  = 0.02;
    static final double P_DRIVE_GAIN = 0.03;

    static final double MAX_CORRECTION = 0.28;

    // -------------------- HEADINGS --------------------
    static final double HEADING_GOAL_DEG     = 0.0;   // after imu.resetYaw()
    static final double HEADING_RIGHT45_DEG = -45.0; // MIRROR of Blue's +45

    // -------------------- STEP COUNTER --------------------
    private int stepNum = 0;
    boolean spunUp = false;

    @Override
    public void runOpMode() {

        // -------------------- MAP HARDWARE --------------------
        leftFrontDrive  = hardwareMap.get(DcMotor.class, "left_front_drive");
        rightFrontDrive = hardwareMap.get(DcMotor.class, "right_front_drive");
        leftBackDrive   = hardwareMap.get(DcMotor.class, "left_back_drive");
        rightBackDrive  = hardwareMap.get(DcMotor.class, "right_back_drive");

        leftLauncher  = hardwareMap.get(DcMotorEx.class, "left_launcher");
        rightLauncher = hardwareMap.get(DcMotorEx.class, "right_launcher");
        leftFeeder    = hardwareMap.get(CRServo.class, "left_feeder");
        rightFeeder   = hardwareMap.get(CRServo.class, "right_feeder");
        diverter      = hardwareMap.get(Servo.class, "diverter");

        intake = hardwareMap.get(DcMotor.class, "intake");

        leftLaunchState = LaunchState.IDLE;
        rightLaunchState = LaunchState.IDLE;

        // Drive directions
        leftFrontDrive.setDirection(DcMotor.Direction.REVERSE);
        rightFrontDrive.setDirection(DcMotor.Direction.FORWARD);
        leftBackDrive.setDirection(DcMotor.Direction.REVERSE);
        rightBackDrive.setDirection(DcMotor.Direction.FORWARD);

        // Launcher + feeder directions
        leftLauncher.setDirection(DcMotorSimple.Direction.REVERSE);
        rightFeeder.setDirection(DcMotorSimple.Direction.REVERSE);

        intake.setDirection(DcMotorSimple.Direction.REVERSE);

        // IMU init
        RevHubOrientationOnRobot.LogoFacingDirection logoDirection = RevHubOrientationOnRobot.LogoFacingDirection.UP;
        RevHubOrientationOnRobot.UsbFacingDirection usbDirection   = RevHubOrientationOnRobot.UsbFacingDirection.BACKWARD;
        imu = hardwareMap.get(IMU.class, "imu");
        imu.initialize(new IMU.Parameters(new RevHubOrientationOnRobot(logoDirection, usbDirection)));

        // Encoders + brake
        setAllModes(DcMotor.RunMode.STOP_AND_RESET_ENCODER);
        setAllModes(DcMotor.RunMode.RUN_USING_ENCODER);
        setAllZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);

        // Launcher config
        leftLauncher.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        rightLauncher.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        leftLauncher.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        rightLauncher.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        leftLauncher.setPIDFCoefficients(DcMotor.RunMode.RUN_USING_ENCODER, new PIDFCoefficients(300, 0, 0, 10));
        rightLauncher.setPIDFCoefficients(DcMotor.RunMode.RUN_USING_ENCODER, new PIDFCoefficients(300, 0, 0, 10));

        leftFeeder.setPower(STOP_SPEED);
        rightFeeder.setPower(STOP_SPEED);
        diverter.setPosition(LEFT_POSITION);

        rightFeeder.setDirection(DcMotorSimple.Direction.REVERSE);

        while (opModeInInit()) {
            telemetry.addLine("Ready: Decode 2026 RED Goal Auto - Far");
            telemetry.addData("Heading (deg)", "%.1f", getHeading());
            telemetry.addData("Counts/Inch", "%.2f", COUNTS_PER_INCH);
            telemetry.addData("Drive/Strafe/Turn", "%.2f / %.2f / %.2f", DRIVE_SPEED, STRAFE_SPEED, TURN_SPEED);
            telemetry.update();
        }

        imu.resetYaw();

        // ==================== AUTON STEPS (RED GOAL / RIGHT SIDE MIRROR) ====================

        step(1, "Start: Back touching RED side perimeter wall; launcher in back");
        leftLauncher.setVelocity(launcherTarget);
        rightLauncher.setVelocity(launcherTarget);
        intake.setPower(1.00);

        step(2, "FIRST SET: STEP1 - Move Forward 8 in, hold 0 deg");
        driveStraight(DRIVE_SPEED, 8, HEADING_GOAL_DEG);

        step(3, "FIRST SET: STEP2 - Turn Right -20 deg");
        turnToHeading(TURN_SPEED, -30);

        sleep(1000); //allow the launcher to attain full velocity

        step(4, "FIRST SET: STEP3 -Shoot first 3 artifacts, wait 2s");
        rightFeeder.setPower(FULL_SPEED);

        diverter.setPosition(0.99); sleep(500);
        diverter.setPosition(0.05); sleep(500);
        diverter.setPosition(0.99); sleep(500);
        diverter.setPosition(0.05); sleep(500);
        rightFeeder.setPower(STOP_SPEED);


        step(5, "FIRST SET: STEP4 - Straighten the angle");
        turnToHeading(TURN_SPEED, 30); //back to the straight facing angle
        sleep(500);

        step(6, "SECOND SET: STEP1 - Forward 8 in, hold 0 deg");
        driveStraight(DRIVE_SPEED, 8.0, 0);

        step(7, "SECOND SET: STEP2 - Turn Right 90 deg");
        turnToHeading(TURN_SPEED, -90);
        sleep(500);

        step(8, "SECOND SET: STEP3 - Forward 43 in, hold 0 deg");
        driveStraight(DRIVE_SPEED, 43.0, 0);

        step(9, "SECOND SET: STEP4 - Forward 43 in, hold 0 deg");
        driveStraight(DRIVE_SPEED, -43.0, 0);

        step(10, "SECOND SET: STEP5 - Turn Left 90 deg");
        turnToHeading(TURN_SPEED, 90);

        step(11, "SECOND SET: STEP6 - Backward 18 in, hold 0 deg");
        driveStraight(DRIVE_SPEED, -8.0, 0);

        step(12, "SECOND SET: STEP7 - Turn Right 20 deg");
        turnToHeading(TURN_SPEED, -30);

        step(13, "SECOND SET: STEP8 -Shoot first 3 artifacts, wait 2s");
        rightFeeder.setPower(FULL_SPEED);

        diverter.setPosition(0.99); sleep(500);
        diverter.setPosition(0.05); sleep(500);
        diverter.setPosition(0.99); sleep(500);
        diverter.setPosition(0.05); sleep(500);
        rightFeeder.setPower(STOP_SPEED);

// LEAVE
        step(9, "LEAVE: Forward 24 in, hold 0 deg");
        driveStraight(DRIVE_SPEED, 24, 0);






        /*
        step(2, "FIRST SET: STEP1 - Move Back 52 in, hold 0 deg");
        driveStraight(DRIVE_SPEED, -52.0, HEADING_GOAL_DEG);

        step(3, "FIRST SET: STEP2 -Shoot first 3 artifacts, wait 2s");
        rightFeeder.setPower(FULL_SPEED);

        diverter.setPosition(0.99); sleep(500);
        diverter.setPosition(0.05); sleep(500);
        diverter.setPosition(0.99); sleep(500);
        diverter.setPosition(0.05); sleep(500);
        rightFeeder.setPower(STOP_SPEED);

        step(4, "SECOND SET: STEP1 - Turn RIGHT to -45 deg");
        turnToHeading(TURN_SPEED, HEADING_RIGHT45_DEG);

        step(5, "SECOND SET: STEP1 - Forward 43 in, hold -45 deg - PICK UP 3");
        driveStraight(DRIVE_SPEED, 43.0, HEADING_RIGHT45_DEG);

        step(6, "SECOND SET: STEP3 - Back 43 in; turn to 0 deg");
        driveStraight(DRIVE_SPEED, -43.0, HEADING_RIGHT45_DEG);
        turnToHeading(TURN_SPEED, HEADING_GOAL_DEG);

        step(7, "SECOND SET: STEP4 - Shoot second 3 artifacts, wait 2s");
        rightFeeder.setPower(FULL_SPEED);
        diverter.setPosition(0.99); sleep(500);
        diverter.setPosition(0.05); sleep(500);
        diverter.setPosition(0.99); sleep(500);
        diverter.setPosition(0.05); sleep(500);
        rightFeeder.setPower(STOP_SPEED);


        step(9, "THIRD SET: STEP1 - Strafe RIGHT 36 in, hold -45 deg");
        strafeDistance(STRAFE_SPEED, 36.0, HEADING_RIGHT45_DEG);

        // 3 SET Trial 02/17/2026 - Start

        /*
        step(8, "Turn RIGHT to -45 deg");
        turnToHeading(TURN_SPEED, HEADING_RIGHT45_DEG);


        step(9, "THIRD SET: STEP1 - Strafe RIGHT 36 in, hold -45 deg");
        strafeDistance(STRAFE_SPEED, 36.0, HEADING_RIGHT45_DEG);

        step(10, "THIRD SET: STEP2 - Forward 42 in, hold -45 deg");
        driveStraight(DRIVE_SPEED, 42.0, HEADING_RIGHT45_DEG);

        step(11, "THIRD SET: STEP3 - Back 42; strafe LEFT 36; turn 0");
        driveStraight(DRIVE_SPEED, -42.0, HEADING_RIGHT45_DEG);
        strafeDistance(STRAFE_SPEED, -36.0, HEADING_RIGHT45_DEG);
        turnToHeading(TURN_SPEED, HEADING_GOAL_DEG);

        step(12, "THIRD SET: STEP4 - Shoot thrid 3 artifacts, wait 2s");
        rightFeeder.setPower(FULL_SPEED);
        diverter.setPosition(0.99); sleep(500);
        diverter.setPosition(0.05); sleep(500);
        diverter.setPosition(0.99); sleep(500);
        diverter.setPosition(0.05); sleep(500);
        rightFeeder.setPower(STOP_SPEED);

        step(13, "Strafe RIGHT 36 in, hold -45 deg: LEAVE");
        strafeDistance(STRAFE_SPEED, 36.0, HEADING_RIGHT45_DEG);
*/
        //3 SET Trial 02/17/2026 - END
/*
        step(11, "Forward 42 in, hold -45 deg");
        driveStraight(DRIVE_SPEED, 42.0, HEADING_RIGHT45_DEG);

        step(12, "Back 42; strafe LEFT 31; turn 0 (return step2 pose)");
        driveStraight(DRIVE_SPEED, -42.0, HEADING_RIGHT45_DEG);
        strafeDistance(STRAFE_SPEED, -31.0, HEADING_RIGHT45_DEG);
        turnToHeading(TURN_SPEED, HEADING_GOAL_DEG);

        step(13, "Shoot third 3 artifacts");
        rightFeeder.setPower(FULL_SPEED);
        diverter.setPosition(0.99); sleep(500);
        diverter.setPosition(0.05); sleep(500);
        rightFeeder.setPower(STOP_SPEED);

        step(14, "Turn RIGHT to -45 deg");
        turnToHeading(TURN_SPEED, HEADING_RIGHT45_DEG);

        step(15, "Strafe RIGHT 30 in, hold -45 deg");
        strafeDistance(STRAFE_SPEED, 30.0, HEADING_RIGHT45_DEG);
*/
        // Stop everything
        stopLauncher();
        intake.setPower(0.00);
        rightLauncher.setPower(0.0);
        leftLauncher.setPower(0.0);

        telemetry.addLine("AUTO COMPLETE");
        telemetry.update();
    }

    // =========================================================================================
    // STEP TELEMETRY
    // =========================================================================================
    private void step(int number, String description) {
        stepNum = number;
        telemetry.addLine("--------------------------------");
        telemetry.addData("STEP", "%d", stepNum);
        telemetry.addData("Action", "%s", description);
        telemetry.addData("Heading (deg)", "%.1f", getHeading());
        telemetry.update();
        sleep(150);
    }

    // =========================================================================================
    // LAUNCHER: Shoot 3 + wait 3 seconds (unused in your current flow)
    // =========================================================================================




    private void stopLauncher() {
        leftLauncher.setVelocity(STOP_SPEED);
        rightLauncher.setVelocity(STOP_SPEED);
        leftFeeder.setPower(STOP_SPEED);
        rightFeeder.setPower(STOP_SPEED);
    }

    // =========================================================================================
    // DRIVE: Encoder moves + IMU heading hold
    // =========================================================================================
    private void driveStraight(double maxDriveSpeed, double distanceInches, double headingDeg) {
        if (!opModeIsActive()) return;

        int moveCounts = (int) Math.round(distanceInches * COUNTS_PER_INCH);

        lfTarget = leftFrontDrive.getCurrentPosition() + moveCounts;
        rfTarget = rightFrontDrive.getCurrentPosition() + moveCounts;
        lbTarget = leftBackDrive.getCurrentPosition() + moveCounts;
        rbTarget = rightBackDrive.getCurrentPosition() + moveCounts;

        setAllTargets(lfTarget, rfTarget, lbTarget, rbTarget);
        setAllModes(DcMotor.RunMode.RUN_TO_POSITION);

        maxDriveSpeed = Math.abs(maxDriveSpeed);
        moveRobot(maxDriveSpeed, 0.0, 0.0);

        while (opModeIsActive() && anyBusy()) {
            double correction = getSteeringCorrection(headingDeg, P_DRIVE_GAIN);
            if (distanceInches < 0) correction *= -1.0;
            correction = Range.clip(correction, -MAX_CORRECTION, MAX_CORRECTION);
            moveRobot(maxDriveSpeed, 0.0, correction);
        }

        moveRobot(0.0, 0.0, 0.0);
        setAllModes(DcMotor.RunMode.RUN_USING_ENCODER);
    }

    private void strafeDistance(double maxStrafeSpeed, double distanceInches, double headingDeg) {
        if (!opModeIsActive()) return;

        int moveCounts = (int) Math.round(distanceInches * COUNTS_PER_INCH);

        // Strafe RIGHT (+): LF+, RF-, LB-, RB+
        lfTarget = leftFrontDrive.getCurrentPosition() + moveCounts;
        rfTarget = rightFrontDrive.getCurrentPosition() - moveCounts;
        lbTarget = leftBackDrive.getCurrentPosition() - moveCounts;
        rbTarget = rightBackDrive.getCurrentPosition() + moveCounts;

        setAllTargets(lfTarget, rfTarget, lbTarget, rbTarget);
        setAllModes(DcMotor.RunMode.RUN_TO_POSITION);

        maxStrafeSpeed = Math.abs(maxStrafeSpeed);
        moveRobot(0.0, maxStrafeSpeed, 0.0);

        while (opModeIsActive() && anyBusy()) {
            double correction = getSteeringCorrection(headingDeg, P_DRIVE_GAIN);
            correction = Range.clip(correction, -MAX_CORRECTION, MAX_CORRECTION);
            moveRobot(0.0, maxStrafeSpeed, correction);
        }

        moveRobot(0.0, 0.0, 0.0);
        setAllModes(DcMotor.RunMode.RUN_USING_ENCODER);
    }

    private void turnToHeading(double maxTurnSpeed, double headingDeg) {
        getSteeringCorrection(headingDeg, P_DRIVE_GAIN);

        while (opModeIsActive() && (Math.abs(headingError) > HEADING_THRESHOLD_DEG)) {
            double turn = getSteeringCorrection(headingDeg, P_TURN_GAIN);
            turn = Range.clip(turn, -maxTurnSpeed, maxTurnSpeed);
            moveRobot(0.0, 0.0, turn);
        }
        moveRobot(0.0, 0.0, 0.0);
    }

    // =========================================================================================
    // DRIVE: Helpers
    // =========================================================================================
    private double getSteeringCorrection(double desiredHeadingDeg, double proportionalGain) {
        targetHeading = desiredHeadingDeg;
        headingError = targetHeading - getHeading();

        while (headingError > 180) headingError -= 360;
        while (headingError <= -180) headingError += 360;

        return Range.clip(headingError * proportionalGain, -1.0, 1.0);
    }

    private void moveRobot(double drive, double strafe, double turn) {
        double lf = drive + strafe - turn;
        double rf = drive - strafe + turn;
        double lb = drive - strafe - turn;
        double rb = drive + strafe + turn;

        double max = Math.max(Math.max(Math.abs(lf), Math.abs(rf)), Math.max(Math.abs(lb), Math.abs(rb)));
        if (max > 1.0) { lf /= max; rf /= max; lb /= max; rb /= max; }

        leftFrontDrive.setPower(lf);
        rightFrontDrive.setPower(rf);
        leftBackDrive.setPower(lb);
        rightBackDrive.setPower(rb);
    }

    private void setAllTargets(int lf, int rf, int lb, int rb) {
        leftFrontDrive.setTargetPosition(lf);
        rightFrontDrive.setTargetPosition(rf);
        leftBackDrive.setTargetPosition(lb);
        rightBackDrive.setTargetPosition(rb);
    }

    private void setAllModes(DcMotor.RunMode mode) {
        leftFrontDrive.setMode(mode);
        rightFrontDrive.setMode(mode);
        leftBackDrive.setMode(mode);
        rightBackDrive.setMode(mode);
    }

    private void setAllZeroPowerBehavior(DcMotor.ZeroPowerBehavior behavior) {
        leftFrontDrive.setZeroPowerBehavior(behavior);
        rightFrontDrive.setZeroPowerBehavior(behavior);
        leftBackDrive.setZeroPowerBehavior(behavior);
        rightBackDrive.setZeroPowerBehavior(behavior);
    }

    private boolean anyBusy() {
        return leftFrontDrive.isBusy() || rightFrontDrive.isBusy() ||
                leftBackDrive.isBusy()  || rightBackDrive.isBusy();
    }

    private double getHeading() {
        YawPitchRollAngles o = imu.getRobotYawPitchRollAngles();
        return o.getYaw(AngleUnit.DEGREES);
    }

}
