// Code Generated by Sidekick is for learning and experimentation purposes only.
package org.firstinspires.ftc.teamcode.notneeded;

import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.Disabled;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.hardware.Servo;

@Autonomous(name = "AutoDiverterServo_6Cycles", group = "Test")
@Disabled
public class AutoDiverterServo_6Cycles extends LinearOpMode {

    private Servo diverter;

    private static final double LEFT_POS  = 0.05;
    private static final double RIGHT_POS = 0.99;

    private static final long DWELL_MS = 3000;
    private static final int CYCLES = 6;

    @Override
    public void runOpMode() {
        diverter = hardwareMap.get(Servo.class, "diverter");

        // If it moves the opposite direction, uncomment:
        // diverter.setDirection(Servo.Direction.REVERSE);

        diverter.setPosition(LEFT_POS);

        waitForStart();
        if (!opModeIsActive()) return;

        for (int i = 0; i < CYCLES && opModeIsActive(); i++) {
            diverter.setPosition(LEFT_POS);
            sleep(DWELL_MS);

            diverter.setPosition(RIGHT_POS);
            sleep(DWELL_MS);
        }

        diverter.setPosition(LEFT_POS);
    }
}
