// Code Generated by Sidekick is for learning and experimentation purposes only.
package org.firstinspires.ftc.teamcode.notneeded;

import com.pedropathing.follower.Follower;
import com.pedropathing.follower.FollowerConstants;
import com.pedropathing.ftc.FollowerBuilder;
import com.pedropathing.ftc.drivetrains.MecanumConstants;
import com.pedropathing.ftc.localization.Encoder;
import com.pedropathing.ftc.localization.constants.DriveEncoderConstants;
import com.pedropathing.geometry.BezierLine;
import com.pedropathing.geometry.Pose;
import com.pedropathing.paths.PathChain;
import com.pedropathing.paths.PathConstraints;
import com.pedropathing.util.Timer;

import com.qualcomm.hardware.rev.RevHubOrientationOnRobot;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.Disabled;
import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.HardwareMap;
import com.qualcomm.robotcore.hardware.IMU;

@Autonomous(name = "V2 Sample Pedro Pathing Autonomous", group = "Autonomous")
@Disabled
public class SampleAutoPathingV2 extends OpMode {

    private Follower follower;
    private Timer pathTimer, opModeTimer;
    private PathState pathState;
    private IMU imu;

    public enum PathState {
        DRIVE_STARTPOS_SHOOT_POS,
        SHOOT_PRELOAD
    }

    private final Pose startPose = new Pose(20.630, 121.981, Math.toRadians(138));
    private final Pose shootPose = new Pose(62.464, 80.836, Math.toRadians(138));

    private PathChain driveStartPosShootPos;

    public void buildPaths() {
        driveStartPosShootPos = follower.pathBuilder()
                .addPath(new BezierLine(startPose, shootPose))
                .setLinearHeadingInterpolation(startPose.getHeading(), shootPose.getHeading())
                .build();
    }

    public void statePathUpdate() {
        switch (pathState) {
            case DRIVE_STARTPOS_SHOOT_POS:
                follower.followPath(driveStartPosShootPos, true);
                setPathState(PathState.SHOOT_PRELOAD);
                break;

            case SHOOT_PRELOAD:
                if (!follower.isBusy()) telemetry.addLine("Done Path1");
                break;

            default:
                telemetry.addLine("No State commanded");
                break;
        }
    }

    public void setPathState(PathState newState) {
        pathState = newState;
        pathTimer.resetTimer();
    }

    @Override
    public void init() {
        // IMU init (your existing setup)
        imu = hardwareMap.get(IMU.class, "imu");
        RevHubOrientationOnRobot revOrientation =
                new RevHubOrientationOnRobot(
                        RevHubOrientationOnRobot.LogoFacingDirection.UP,
                        RevHubOrientationOnRobot.UsbFacingDirection.BACKWARD
                );
        imu.initialize(new IMU.Parameters(revOrientation));

        // Set BRAKE only here. (Motor directions are set in PedroConstants to match TeleOp.)
        DcMotor leftFrontDrive = hardwareMap.get(DcMotor.class, "left_front_drive");
        DcMotor rightFrontDrive = hardwareMap.get(DcMotor.class, "right_front_drive");
        DcMotor leftBackDrive = hardwareMap.get(DcMotor.class, "left_back_drive");
        DcMotor rightBackDrive = hardwareMap.get(DcMotor.class, "right_back_drive");

        leftFrontDrive.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        rightFrontDrive.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        leftBackDrive.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        rightBackDrive.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);

        pathState = PathState.DRIVE_STARTPOS_SHOOT_POS;
        pathTimer = new Timer();
        opModeTimer = new Timer();

        // Build follower with drivetrain + localizer (prevents Localizer null NPE)
        follower = PedroConstants.createFollower(hardwareMap);

        buildPaths();
        follower.setPose(startPose);
    }

    @Override
    public void start() {
        opModeTimer.resetTimer();
        setPathState(pathState);
    }

    @Override
    public void loop() {
        follower.update();
        statePathUpdate();

        telemetry.addData("path state", pathState.toString());
        telemetry.addData("x", follower.getPose().getX());
        telemetry.addData("y", follower.getPose().getY());
        telemetry.addData("heading", follower.getPose().getHeading());
        telemetry.addData("path time", pathTimer.getElapsedTimeSeconds());
        telemetry.update();
    }

    /**
     * Combined “Constants” embedded so you can’t accidentally call a null-localizer build.
     */
    public static class PedroConstants {

        public static final FollowerConstants followerConstants = new FollowerConstants();

        // Keep yours if you want; defaultConstraints is fine too
        public static final PathConstraints pathConstraints = new PathConstraints(0.99, 100, 1, 1);

        public static Follower createFollower(HardwareMap hardwareMap) {

            // --- Drivetrain (MATCHES your working TeleOp directions) ---
            MecanumConstants mec = new MecanumConstants();
            mec.leftFrontMotorName = "left_front_drive";
            mec.rightFrontMotorName = "right_front_drive";
            mec.leftRearMotorName = "left_back_drive";
            mec.rightRearMotorName = "right_back_drive";

            // not working 1
            //mec.leftFrontMotorName  = "right_front_drive";
            // mec.rightFrontMotorName = "left_front_drive";
            //mec.leftRearMotorName   = "right_back_drive";
            // mec.rightRearMotorName  = "left_back_drive";

            // TeleOp:
            // LF REVERSE, LB REVERSE, RF FORWARD, RB FORWARD
            //mec.leftFrontMotorDirection  = DcMotorSimple.Direction.REVERSE;
            //mec.leftRearMotorDirection   = DcMotorSimple.Direction.REVERSE;
            //mec.rightFrontMotorDirection = DcMotorSimple.Direction.FORWARD;
            //mec.rightRearMotorDirection  = DcMotorSimple.Direction.FORWARD;

            //mec.leftFrontMotorDirection  = DcMotorSimple.Direction.REVERSE;
            //mec.leftRearMotorDirection   = DcMotorSimple.Direction.REVERSE;
            //mec.rightFrontMotorDirection = DcMotorSimple.Direction.FORWARD;
            //mec.rightRearMotorDirection  = DcMotorSimple.Direction.FORWARD;

            // --- Localizer (Drive encoders) ---
            DriveEncoderConstants dec = new DriveEncoderConstants();

            // If using built-in motor encoders, these should match motor names.
            // If using separate odometry pods, replace with those configured device names.
            dec.leftFrontMotorName = "left_front_drive";
            dec.rightFrontMotorName = "right_front_drive";
            dec.leftRearMotorName = "left_back_drive";
            dec.rightRearMotorName = "right_back_drive";

            // not working 1
            //dec.leftFrontMotorName  = "right_front_drive";
            //dec.rightFrontMotorName = "left_front_drive";
            //dec.leftRearMotorName   = "right_back_drive";
            //dec.rightRearMotorName  = "left_back_drive";


            // Encoder direction signs (typically match the side directions with motor encoders)
            dec.leftFrontEncoderDirection = Encoder.REVERSE;
            dec.rightFrontEncoderDirection = Encoder.FORWARD;
            dec.leftRearEncoderDirection = Encoder.REVERSE;
            dec.rightRearEncoderDirection = Encoder.FORWARD;

            return new FollowerBuilder(followerConstants, hardwareMap)
                    .pathConstraints(pathConstraints)
                    .mecanumDrivetrain(mec)
                    .driveEncoderLocalizer(dec) // <- ensures localizer is NOT null
                    .build();
        }
    }
}