// Code Generated by Sidekick is for learning and experimentation purposes only.
package org.firstinspires.ftc.teamcode.notneeded;

import com.qualcomm.hardware.rev.RevHubOrientationOnRobot;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.qualcomm.robotcore.eventloop.opmode.Disabled;
import com.qualcomm.robotcore.eventloop.opmode.LinearOpMode;
import com.qualcomm.robotcore.hardware.CRServo;
import com.qualcomm.robotcore.hardware.DcMotor;
import com.qualcomm.robotcore.hardware.DcMotorEx;
import com.qualcomm.robotcore.hardware.DcMotorSimple;
import com.qualcomm.robotcore.hardware.IMU;
import com.qualcomm.robotcore.hardware.PIDFCoefficients;
import com.qualcomm.robotcore.hardware.Servo;
import com.qualcomm.robotcore.util.ElapsedTime;
import com.qualcomm.robotcore.util.Range;

import org.firstinspires.ftc.robotcore.external.navigation.AngleUnit;
import org.firstinspires.ftc.robotcore.external.navigation.YawPitchRollAngles;

@Autonomous(name = "Switcher Auto)", group = "Robot")
@Disabled
public class SwitcherAuto extends LinearOpMode {

    // -------------------- DRIVE --------------------
    private DcMotor leftFrontDrive, rightFrontDrive, leftBackDrive, rightBackDrive;
    private IMU imu;

    private double headingError = 0.0;
    private double targetHeading = 0.0;

    private int lfTarget = 0, rfTarget = 0, lbTarget = 0, rbTarget = 0;

    // -------------------- LAUNCHER (from your TeleOp) --------------------
    private DcMotorEx leftLauncher, rightLauncher;
    private CRServo leftFeeder, rightFeeder;
    private Servo diverter;
    private DcMotor intake = null;
    ElapsedTime leftFeederTimer = new ElapsedTime();
    ElapsedTime rightFeederTimer = new ElapsedTime();

    private enum IntakeState {
        ON,
        OFF;
    }

    private enum LaunchState {
        IDLE,
        SPIN_UP,
        LAUNCH,
        LAUNCHING,
    }

    private LaunchState leftLaunchState;
    private LaunchState rightLaunchState;

    private enum DiverterDirection {
        LEFT,
        RIGHT;
    }

    private DiverterDirection diverterDirection = DiverterDirection.LEFT;
    private IntakeState intakeState = IntakeState.OFF;

    private static final double FEED_TIME_SECONDS = 0.80;
    private static final double STOP_SPEED = 0.0;
    private static final double FULL_SPEED = 1.0;

    private static final double LAUNCHER_CLOSE_TARGET_VELOCITY = 1200; // ticks/sec
    private static final double LAUNCHER_CLOSE_MIN_VELOCITY = 1175;

    private double launcherTarget = LAUNCHER_CLOSE_TARGET_VELOCITY;
    private double launcherMin = LAUNCHER_CLOSE_MIN_VELOCITY;

    private static final double LEFT_POSITION = 0.2962;
    private static final double RIGHT_POSITION = 0.0;

    // -------------------- COUNTS/INCH --------------------
    static final double COUNTS_PER_MOTOR_REV = 537.7;          // Yellow Jacket 312RPM (typical)
    static final double DRIVE_GEAR_REDUCTION = 1.0;            // change if external gearing
    static final double WHEEL_DIAMETER_INCHES = 104.0 / 25.4;   // Ø104mm
    static final double COUNTS_PER_INCH =
            (COUNTS_PER_MOTOR_REV * DRIVE_GEAR_REDUCTION) / (WHEEL_DIAMETER_INCHES * Math.PI);

    // -------------------- TUNABLES --------------------
    static final double DRIVE_SPEED = 0.80; // per your request
    static final double STRAFE_SPEED = 0.60; // keep lower for accuracy
    static final double TURN_SPEED = 0.25;

    static final double HEADING_THRESHOLD_DEG = 1.0;
    static final double P_TURN_GAIN = 0.02;
    static final double P_DRIVE_GAIN = 0.03;

    static final double MAX_CORRECTION = 0.28;

    // -------------------- HEADINGS --------------------
    static final double HEADING_GOAL_DEG = 0.0;  // after imu.resetYaw()
    static final double HEADING_LEFT45_DEG = 45.0;

    // -------------------- STEP COUNTER --------------------
    private int stepNum = 0;

    private Servo.Direction divertorDirection;

    @Override
    public void runOpMode() {

        // -------------------- MAP HARDWARE --------------------
        leftFrontDrive = hardwareMap.get(DcMotor.class, "left_front_drive");
        rightFrontDrive = hardwareMap.get(DcMotor.class, "right_front_drive");
        leftBackDrive = hardwareMap.get(DcMotor.class, "left_back_drive");
        rightBackDrive = hardwareMap.get(DcMotor.class, "right_back_drive");

        leftLauncher = hardwareMap.get(DcMotorEx.class, "left_launcher");
        rightLauncher = hardwareMap.get(DcMotorEx.class, "right_launcher");
        leftFeeder = hardwareMap.get(CRServo.class, "left_feeder");
        rightFeeder = hardwareMap.get(CRServo.class, "right_feeder");
        diverter = hardwareMap.get(Servo.class, "diverter");

        intake = hardwareMap.get(DcMotor.class, "intake");

        leftLaunchState = LaunchState.IDLE;
        rightLaunchState = LaunchState.IDLE;

        // Drive directions (per your earlier setup)
        leftFrontDrive.setDirection(DcMotor.Direction.REVERSE);
        rightFrontDrive.setDirection(DcMotor.Direction.FORWARD);
        leftBackDrive.setDirection(DcMotor.Direction.REVERSE);
        rightBackDrive.setDirection(DcMotor.Direction.FORWARD);

        // Launcher + feeder directions (from your TeleOp)
        leftLauncher.setDirection(DcMotorSimple.Direction.REVERSE);
        rightFeeder.setDirection(DcMotorSimple.Direction.REVERSE);

        intake.setDirection(DcMotorSimple.Direction.REVERSE);

        // IMU init (edit if hub orientation differs)
        RevHubOrientationOnRobot.LogoFacingDirection logoDirection = RevHubOrientationOnRobot.LogoFacingDirection.UP;
        RevHubOrientationOnRobot.UsbFacingDirection usbDirection = RevHubOrientationOnRobot.UsbFacingDirection.BACKWARD;
        imu = hardwareMap.get(IMU.class, "imu");
        imu.initialize(new IMU.Parameters(new RevHubOrientationOnRobot(logoDirection, usbDirection)));

        // Encoders + brake
        setAllModes(DcMotor.RunMode.STOP_AND_RESET_ENCODER);
        setAllModes(DcMotor.RunMode.RUN_USING_ENCODER);
        setAllZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);

        // Launcher config
        leftLauncher.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        rightLauncher.setZeroPowerBehavior(DcMotor.ZeroPowerBehavior.BRAKE);
        leftLauncher.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        rightLauncher.setMode(DcMotor.RunMode.RUN_USING_ENCODER);
        leftLauncher.setPIDFCoefficients(DcMotor.RunMode.RUN_USING_ENCODER, new PIDFCoefficients(300, 0, 0, 10));
        rightLauncher.setPIDFCoefficients(DcMotor.RunMode.RUN_USING_ENCODER, new PIDFCoefficients(300, 0, 0, 10));

        leftFeeder.setPower(STOP_SPEED);
        rightFeeder.setPower(STOP_SPEED);
        diverter.setPosition(LEFT_POSITION);

        rightFeeder.setDirection(DcMotorSimple.Direction.REVERSE);

        while (opModeInInit()) {
            telemetry.addLine("Ready: Decode 2026 Blue Goal Auto V4");
            telemetry.addData("Heading (deg)", "%.1f", getHeading());
            telemetry.addData("Counts/Inch", "%.2f", COUNTS_PER_INCH);
            telemetry.addData("Drive/Strafe/Turn", "%.2f / %.2f / %.2f", DRIVE_SPEED, STRAFE_SPEED, TURN_SPEED);
            telemetry.update();
        }

        //sleep(3000);
        divertorDirection = diverter.getDirection();
        reverseDivertorDirection(divertorDirection);
        diverter.setPosition(0.8);
        telemetry.addLine("Ready: First Flap: pos 0.8");
        double currentPos = diverter.getPosition();
        sleep(3000);

       // reverseDivertorDirection(divertorDirection);
        diverter.setPosition(0);
        telemetry.addLine("Ready: Second Flap: pos 0");
        sleep(3000);

        reverseDivertorDirection(divertorDirection);
        diverter.setPosition(0.8);
        telemetry.addLine("Ready: Third Flap: pos 0.8");
        sleep(3000);
        imu.resetYaw();

        // ==================== AUTON STEPS (your latest list) ====================
      /*  telemetry.addLine("--------------------------------");
        telemetry.addLine("TURN RIGHT");
        diverterDirection = DiverterDirection.LEFT;
        switchDiverterDirection(diverterDirection);
        sleep(3000);

        telemetry.addLine("--------------------------------");
        telemetry.addLine("TURN LEFT");
        diverterDirection = DiverterDirection.RIGHT;
        switchDiverterDirection(diverterDirection);
        sleep(3000);

        telemetry.addLine("--------------------------------");
        telemetry.addLine("TURN RIGHT");
        diverterDirection = DiverterDirection.LEFT;
        switchDiverterDirection(diverterDirection);
        sleep(3000);
        */
    }

    private void reverseDivertorDirection(Servo.Direction divertorDirection) {

        if(divertorDirection== Servo.Direction.REVERSE){
            diverter.setDirection(Servo.Direction.FORWARD);
        } else{
            diverter.setDirection(Servo.Direction.REVERSE);
        }
    }

    // =========================================================================================
    // STEP TELEMETRY
    // =========================================================================================
    private void step(int number, String description) {
        stepNum = number;
        telemetry.addLine("--------------------------------");
        telemetry.addData("STEP", "%d", stepNum);
        telemetry.addData("Action", "%s", description);
        telemetry.addData("Heading (deg)", "%.1f", getHeading());
        telemetry.update();
        sleep(150);
    }

    // =========================================================================================
    // LAUNCHER: Shoot 3 + wait 3 seconds
    // =========================================================================================
    private void shoot3ArtifactsAndWait3s() {
        boolean spunUp = spinUpLauncher(1.25);

        if (spunUp && opModeIsActive()) {
            fireOneShotRight();
            // diverter.setPosition(1.0);
            //switchDiverterDirection (diverterDirection);

            fireOneShotRight();
            //diverter.setPosition(0.0);
            //switchDiverterDirection (diverterDirection);

            fireOneShotRight();
            // diverter.setPosition(1.0);
            //switchDiverterDirection (diverterDirection);
            rightFeeder.setPower(STOP_SPEED);
        }

        //sleep(3000); sleep already in firing shot
        //stopLauncher();
    }

    private boolean spinUpLauncher(double timeoutSeconds) {
        leftLauncher.setVelocity(launcherTarget);
        rightLauncher.setVelocity(launcherTarget);

        long start = System.currentTimeMillis();
        while (opModeIsActive() && (System.currentTimeMillis() - start) < (long) (timeoutSeconds * 1000.0)) {
            if (rightLauncher.getVelocity() >= launcherMin) return true;
            //telemetry.addData("STEP %d Launcher", stepNum, "Spin-up");
            telemetry.addData("Vel L/R", "%.0f / %.0f", leftLauncher.getVelocity(), rightLauncher.getVelocity());
            telemetry.update();
            sleep(10);
        }
        return rightLauncher.getVelocity() >= launcherMin;
    }

    private void fireOneShotRight() {
        //if (!opModeIsActive()) return;
        rightFeeder.setPower(FULL_SPEED);
        switchDiverterDirection(diverterDirection);
        sleep((long) (FEED_TIME_SECONDS * 1000.0));
        //rightFeeder.setPower(STOP_SPEED);
        //sleep(150);
    }

    void launchRight(boolean shotRequested) {
        switch (rightLaunchState) {
            case IDLE:
                if (shotRequested) {
                    rightLaunchState = LaunchState.SPIN_UP;
                }
                break;
            case SPIN_UP:
                leftLauncher.setVelocity(launcherTarget);
                rightLauncher.setVelocity(launcherTarget);
                if (rightLauncher.getVelocity() > launcherMin) {
                    rightLaunchState = LaunchState.LAUNCH;
                }
                break;
            case LAUNCH:
                rightFeeder.setPower(FULL_SPEED);
                rightFeederTimer.reset();
                rightLaunchState = LaunchState.LAUNCHING;
                break;
            case LAUNCHING:
                if (rightFeederTimer.seconds() > FEED_TIME_SECONDS) {
                    rightLaunchState = LaunchState.IDLE;
                    rightFeeder.setPower(STOP_SPEED);
                }
                break;
        }
    }

    private void stopLauncher() {
        leftLauncher.setVelocity(STOP_SPEED);
        rightLauncher.setVelocity(STOP_SPEED);
        leftFeeder.setPower(STOP_SPEED);
        rightFeeder.setPower(STOP_SPEED);
    }

    // =========================================================================================
    // DRIVE: Encoder moves + IMU heading hold
    // =========================================================================================
    private void driveStraight(double maxDriveSpeed, double distanceInches, double headingDeg) {
        if (!opModeIsActive()) return;

        int moveCounts = (int) Math.round(distanceInches * COUNTS_PER_INCH);

        lfTarget = leftFrontDrive.getCurrentPosition() + moveCounts;
        rfTarget = rightFrontDrive.getCurrentPosition() + moveCounts;
        lbTarget = leftBackDrive.getCurrentPosition() + moveCounts;
        rbTarget = rightBackDrive.getCurrentPosition() + moveCounts;

        setAllTargets(lfTarget, rfTarget, lbTarget, rbTarget);
        setAllModes(DcMotor.RunMode.RUN_TO_POSITION);

        maxDriveSpeed = Math.abs(maxDriveSpeed);
        moveRobot(maxDriveSpeed, 0.0, 0.0);

        while (opModeIsActive() && anyBusy()) {
            double correction = getSteeringCorrection(headingDeg, P_DRIVE_GAIN);
            if (distanceInches < 0) correction *= -1.0;
            correction = Range.clip(correction, -MAX_CORRECTION, MAX_CORRECTION);
            moveRobot(maxDriveSpeed, 0.0, correction);
        }

        moveRobot(0.0, 0.0, 0.0);
        setAllModes(DcMotor.RunMode.RUN_USING_ENCODER);
    }

    private void strafeDistance(double maxStrafeSpeed, double distanceInches, double headingDeg) {
        if (!opModeIsActive()) return;

        int moveCounts = (int) Math.round(distanceInches * COUNTS_PER_INCH);

        // Strafe RIGHT (+): LF+, RF-, LB-, RB+
        lfTarget = leftFrontDrive.getCurrentPosition() + moveCounts;
        rfTarget = rightFrontDrive.getCurrentPosition() - moveCounts;
        lbTarget = leftBackDrive.getCurrentPosition() - moveCounts;
        rbTarget = rightBackDrive.getCurrentPosition() + moveCounts;

        setAllTargets(lfTarget, rfTarget, lbTarget, rbTarget);
        setAllModes(DcMotor.RunMode.RUN_TO_POSITION);

        maxStrafeSpeed = Math.abs(maxStrafeSpeed);
        moveRobot(0.0, maxStrafeSpeed, 0.0);

        while (opModeIsActive() && anyBusy()) {
            double correction = getSteeringCorrection(headingDeg, P_DRIVE_GAIN);
            correction = Range.clip(correction, -MAX_CORRECTION, MAX_CORRECTION);
            moveRobot(0.0, maxStrafeSpeed, correction);
        }

        moveRobot(0.0, 0.0, 0.0);
        setAllModes(DcMotor.RunMode.RUN_USING_ENCODER);
    }

    private void turnToHeading(double maxTurnSpeed, double headingDeg) {
        getSteeringCorrection(headingDeg, P_DRIVE_GAIN);

        while (opModeIsActive() && (Math.abs(headingError) > HEADING_THRESHOLD_DEG)) {
            double turn = getSteeringCorrection(headingDeg, P_TURN_GAIN);
            turn = Range.clip(turn, -maxTurnSpeed, maxTurnSpeed);
            moveRobot(0.0, 0.0, turn);
        }
        moveRobot(0.0, 0.0, 0.0);
    }

    // =========================================================================================
    // DRIVE: Helpers
    // =========================================================================================
    private double getSteeringCorrection(double desiredHeadingDeg, double proportionalGain) {
        targetHeading = desiredHeadingDeg;
        headingError = targetHeading - getHeading();

        while (headingError > 180) headingError -= 360;
        while (headingError <= -180) headingError += 360;

        return Range.clip(headingError * proportionalGain, -1.0, 1.0);
    }

    private void moveRobot(double drive, double strafe, double turn) {
        double lf = drive + strafe - turn;
        double rf = drive - strafe + turn;
        double lb = drive - strafe - turn;
        double rb = drive + strafe + turn;

        double max = Math.max(Math.max(Math.abs(lf), Math.abs(rf)), Math.max(Math.abs(lb), Math.abs(rb)));
        if (max > 1.0) {
            lf /= max;
            rf /= max;
            lb /= max;
            rb /= max;
        }

        leftFrontDrive.setPower(lf);
        rightFrontDrive.setPower(rf);
        leftBackDrive.setPower(lb);
        rightBackDrive.setPower(rb);
    }

    private void setAllTargets(int lf, int rf, int lb, int rb) {
        leftFrontDrive.setTargetPosition(lf);
        rightFrontDrive.setTargetPosition(rf);
        leftBackDrive.setTargetPosition(lb);
        rightBackDrive.setTargetPosition(rb);
    }

    private void setAllModes(DcMotor.RunMode mode) {
        leftFrontDrive.setMode(mode);
        rightFrontDrive.setMode(mode);
        leftBackDrive.setMode(mode);
        rightBackDrive.setMode(mode);
    }

    private void setAllZeroPowerBehavior(DcMotor.ZeroPowerBehavior behavior) {
        leftFrontDrive.setZeroPowerBehavior(behavior);
        rightFrontDrive.setZeroPowerBehavior(behavior);
        leftBackDrive.setZeroPowerBehavior(behavior);
        rightBackDrive.setZeroPowerBehavior(behavior);
    }

    private boolean anyBusy() {
        return leftFrontDrive.isBusy() || rightFrontDrive.isBusy() ||
                leftBackDrive.isBusy() || rightBackDrive.isBusy();
    }

    private double getHeading() {
        YawPitchRollAngles o = imu.getRobotYawPitchRollAngles();
        return o.getYaw(AngleUnit.DEGREES);
    }

    private void switchDiverterDirection(DiverterDirection diverterDirectionVar) {
        switch (diverterDirectionVar) {
            case LEFT:
                //diverterDirection = DiverterDirection.RIGHT;
                diverter.setPosition(RIGHT_POSITION);
                break;
            case RIGHT:
                //diverterDirection = DiverterDirection.LEFT;
                diverter.setPosition(LEFT_POSITION);
                break;
        }

    }

}
